### PR TITLE
[Gitcoin] Uniswap trading of ADX token

### PR DESCRIPTION
**Pull request by Bobface**
## Uniswap Integration
The repository at https://github.com/Bobface/uniswap-solidity implements a mock Uniswap which enables the ADX token to be traded against tokens listed on the official Uniswap. The market needs to be seeded with ADX and ETH. 

The deployment to Mainnet and Etherscan verification is handled by Truffle (see below). 

## Contract addresses

The official Uniswap and ADX contract addresses are set in `migrations/2_deploy.js` and are currently:

```
adxMainnet = "0x4470BB87d77b963A013DB939BE332f927f2b992e"
uniswapMainnet = "0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95"
```

## Usage

Clone the repo linked above, then

1. Run `yarn` to install dependencies
2. Create a `.env` file in the directory root. The `.env` file specifies three parameters:
```
INFURA_KEY=...
PRIVATE_KEY=0x...
ETHERSCAN_KEY=...
```
The private key will be used for deployment on Mainnet. 

3. Run `truffle migrate --reset --network mainnet` to deploy to Mainnet.
4. Run `truffle run verify UniswapFactory --network mainnet` to verify the contract on Etherscan.

On deployment, an exchange for ADX/ETH will be automatically created. This exchange needs to be seeded with ADX and ETH. 

If someone wants to trade ADX for DAI, the exchange will swap ADX for ETH and then ETH for DAI on the official Uniswap.

### CODE REVIEW

**Comment by vbstreetz** [comment]
@Bobface did you succeed in deploying? I see there was an attempt 1 yr ago `0x4470BB87d77b963A013DB939BE332f927f2b992e`.

**Comment by Bobface** [comment]
@vbstreetz I have not yet tried to deploy the contract because of extremely high gas prices in the last days. I hope to be able to deploy today. 

Also, I was contacted by a Bancor dev about this bounty. He told me that it is possible to trade the ADX token on Bancor as-is. If that's an option for you you can also list the token there.

**Comment by vbstreetz** [comment]
Awesome. Great solution btw 🙂

**Comment by Ivshti** [comment]
Uniswap v2 solves this, so we're going to close this

**Pull request closed without merging**
